# fly.toml app configuration file generated for bom-laravel on 2023-12-10T01:19:40+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bom-laravel"
primary_region = "sin"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "development"
  APP_URL = "https://bom-api.rugefx.com"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "debug"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"
  DB_CONNECTION = "pgsql"
  SESSION_DOMAIN = ".rugefx.com"
  SANCTUM_STATEFUL_DOMAINS = "bom-api.rugefx.com,bom.rugefx.com"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
